### ISSUE TITLE
Allow non google users to play

### ISSUE THREAD

**Issue by Sarabadu** [durancristhian/cremona#1]
For family or friends(people that we already know). it will be nice to have an option that does not require Login.

i understood that this is out of scope for now but in the future maybe can be a configurable feature.

**Comment by durancristhian** [comment]
Hey, this is a great idea even when I consider it "out of scope" for the streamings. I think this options might work if we just have an extra config on the game saying how players can join your challenge and play. If requires login, we use what we have, if not, just. ask for a name and show must go on :D

**Comment by durancristhian** [comment]
I'll keep this issue because I'll implement it someday :)
